### ISSUE TITLE
Problems launching virtual box

### ISSUE THREAD

**Issue by andrewbattista** [NYULibraries/spatial_data_repository#47]
Upon running the final command ```bundle exec rake sdr:server``` the following error is thrown:

```rake aborted!
Failed to execute solr create: INFO  - 2019-11-15 20:17:16.976; org.apache.solr.util.configuration.SSLCredentialProviderFactory; Processing SSL Credential Provider chain: env;sysprop

ERROR: 
Core 'sdr-core-development' already exists!
Checked core existence using Core API command:
http://localhost:8983/solr/admin/cores?action=STATUS&core=sdr-core-development

. Further information may be available in tmp/sdr-core-development/logs/usr/local/rvm/gems/ruby-2.5.5/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:321:in `exec'
/usr/local/rvm/gems/ruby-2.5.5/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:158:in `create'
/usr/local/rvm/gems/ruby-2.5.5/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:215:in `with_collection'
/vagrant/sdr/lib/tasks/sdr.rake:24:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:64:in `wrap'
/usr/local/rvm/gems/ruby-2.5.5/gems/solr_wrapper-2.1.0/lib/solr_wrapper.rb:43:in `wrap'
/vagrant/sdr/lib/tasks/sdr.rake:23:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => sdr:server
```
Seems to be an issue where the Solr core already exists?

**Comment by ewlarson** [comment]
This is pretty common issue developing on a Blacklight instance with SolrWrapper:
https://github.com/cbeer/solr_wrapper/issues/69

Just take a look in your Rails.root tmp directory and remove (`rm -r -f`) sdr-core-development if it already exists. Once it's gone, SolrWrapper will start up again properly.

**Comment by andrewbattista** [comment]
Thank you @ewlarson!!!! #sharedknowledge

**Comment by andrewbattista** [comment]
Just to follow through, this fix works! If this error occurs, go to ```tmp/solr-core-development/solr``` and then delete the folder called ```solr-core-development```

**Comment by mnyrop** [comment]
🎉
I'll add a line in the vagrant shell provisioning that removes this directory if it exists.
